language: node_js
os:
  - windows
  - linux
  - osx
notifications:
  email: false
node_js:
  - "16.18.0"
cache:
  npm: true,
  directories:
    - "node_modules"
before_script:
  - npm prune
script:
  - npm run test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
